openapi: "3.0.0"

info:
  description: "Codegen for mstraining service"
  version: "0.0.1"
  title: "Microservices API Specification"
  contact:
    email: "hernan.tenjo@gmail.com"

tags:
  - name: "passenger"
    description: "Passenger tag for demo purposes"

servers:
  - url: http://localhost:8080/
    description: "localhost"

paths:
  /passenger/{passengerId}:
    get:
      tags:
        - "passenger"
      summary: "Retrieves the passenger info by ID"
      operationId: "getPassengerUserDetails"
      parameters:
        - name: "passengerId"
          in: "path"
          description: "retrieves user by passenger by id"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        200:
          description: "Passenger information is retrieved by id"
          content:
            application/json:
              schema:
                type: "object"
                $ref: '#/components/schemas/Passenger'
components:
  schemas:
    Passenger:
      type: "object"
      required:
        - "id"
        - "firstName"
        - "lastName"
        - "dateOfBirth"
        - "gender"
      properties:
        id:
          type: "integer"
          format: "int64"
        firstName:
          type: "string"
          example: "John"
        lastName:
          type: "string"
          example: "Smith"
        dateOfBirth:
          type: "string"
          example: "1992-10-05"
        gender:
          type: "string"
          enum:
            - "MALE"
            - "FEMALE"
            - "OTHER"